# Generated by Django 3.2.7 on 2021-09-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of the Group')),
                ('description', models.TextField(verbose_name='Description')),
                ('actions', models.CharField(choices=[('edit', 'Edit'), ('delete', 'Delete')], default='edit', max_length=50)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'List of Groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User nickname')),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('actions', models.CharField(choices=[('edit', 'Edit User'), ('delete', 'Delete User')], default='edit', max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'list of Users',
            },
        ),
    ]
